### ISSUE TITLE
css .aligned label miss with rtl languages original css

### ISSUE THREAD

**Issue by Oalamoud** [s-block/django-nested-inline#69]
The problem is when dealing with rtl languages your custom css override the rtl.css file
The Only problem I have seen where with label going all the way to the left
Here is a quick fix 
```css 
.aligned label {
    display: block;
    padding: 3px 10px 0 0;
    float: left; /*delete this line to fix the problem line:66*/
    width: 8em;
}
```
after deleting the cause of this problem `float:left;`
```css 
.aligned label {
    display: block;
    padding: 3px 10px 0 0;
    width: 8em;
}
```
This is working well with rtl languages
